CODIGO_NORMAL: str = 'NM'
CODIGO_PRIORITARIO: str = 'PR'

TAMANHO_PADRAO_MAXIMO: int = 300
TAMANHO_PADRAO_MINIMO: int = 0
INCREMENTO_CODIGO_FILA: int = 10

TP_FILA_NORMAL: int = 1
TP_FILA_PRIORITARIA: int = 2
